### ISSUE TITLE
iOS 12 CIKernel Filters CRASH

### ISSUE THREAD

**Issue by abhi-dave** [FlexMonkey/Filterpedia#30]
Many of the Filters Including EightBit, CRT, Bayer Dither, Lens Flare, Lens Correction etc.  based on CIKernel are crashing due to new changes.

`ERROR: parameter has unexpected type 'vec4' (should be a sampler type)
   vec2 uv = samplerCoord(image); `

This seems to be a common error message among most crashing filters. please check.

**Comment by FlexMonkey** [comment]
Sorry, I'm no longer able to maintain these repositories.

**Comment by abhi-dave** [comment]
At least let the issue remain open so that others facing the same issue can discuss the problem. 

Thank you for this cool repo though! 👍

**Comment by FlexMonkey** [comment]
No probs. Reopened.

**Comment by ilkayaktas** [comment]
Hi all, did anybody find a solution for this problem?

**Comment by abhi-dave** [comment]
Hello @ilkayaktas ,

try converting  CIColorKernel Filters to CIKernel Filters, this solves the problem for me.

**Comment by enriqueg** [comment]
I submitted the bug to Apple, and this is their response:

Engineering has determined that this issue behaves as intended based on the following information: 
If it ever worked, it shouldn’t have and while we were doing the work for supporting new language features, we also got that bug out of the way.
We consider this issue closed.

Go for CIKernel :)

**Comment by bizibizi** [comment]
@ilkayaktas @abhiperry  can you share a working code please?

**Comment by TareObjects** [comment]
> Hi all, did anybody find a solution for this problem?

here's working code.

```        let crtColorKernel = CIKernel(source: """
      kernel vec4 crtColor(sampler image, float pixelWidth, float pixelHeight)
      {
        vec2 v2 =   destCoord();
        vec4 v4 =   sample(image, samplerTransform(image, v2));
        int columnIndex = int(mod(v2.x / pixelWidth, 3.0));
        int rowIndex = int(mod(v2.y, pixelHeight));
        float scanlineMultiplier = (rowIndex == 0 || rowIndex == 1) ? 0.3 : 1.0;
        float red = (columnIndex == 0) ? v4.r : v4.r * ((columnIndex == 2) ? 0.3 : 0.2);
        float green = (columnIndex == 1) ? v4.g : v4.g * ((columnIndex == 2) ? 0.3 : 0.2);
        float blue = (columnIndex == 2) ? v4.b : v4.b * 0.2;
        return vec4(red * scanlineMultiplier, green * scanlineMultiplier, blue * scanlineMultiplier, 1.0);
      }
    """)

...

        override var outputImage: CIImage! {
            if
                let inputImage = inputImage,
                let crtColorKernel = crtColorKernel {
                let dod = inputImage.extent
                let args = [inputImage, pixelWidth, pixelHeight] as [Any]
                let roiCallback = { (index: Int32, rect: CGRect) -> CGRect in
                    return rect
                }
                return crtColorKernel.apply(extent: dod, roiCallback: roiCallback, arguments: args)
            }
            return nil
        }
```

**Comment by rhoeper** [comment]
The issues noted above and Filterpedia have been updated in the following Fork to iOS 12, Swift 4.0 using Xcode 10.1. Please note that the Core Image Kernel Language API has been deprecated in iOS 12 and support may disappear with some future iOS.

https://github.com/rhoeper?tab=repositories

Thanks to raceWalkWill, https://github.com/racewalkWill/Filterpedia-Swift4 , the Metal Filters have  also been recently updated and added to the above Fork.

And thanks go to Simon, for all his hard work building Filterpedia.

**Comment by baymak** [comment]
Hello Richard/Simon
many thanks for the original repo and updated repo.It is hard work and very useful. I discovered it recently and I wanted to check "HistogramSpecification" code to work. As it is disabled I reenabled it but it crashes at vImageHistogramSpecification_ARGB8888 line execution. It gives Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) error. I could not figure out what is going wrong with that? Do you have any recommendation where to look?

**Comment by FlexMonkey** [comment]
I'd suggest looking at Apple's own histogram specification sample - https://developer.apple.com/documentation/accelerate/specifying_histograms_with_vimage.

**Comment by baymak** [comment]
Thanks Simon,
I already developed my code by using Apple's sample but I wonder your solution when I saw some comments are different.

**Comment by FlexMonkey** [comment]
My version is ancient! You should use Apple's code over mine 🙂
