### ISSUE TITLE
No such module 'MetalKit' / a way to run the app in the simulator

### ISSUE THREAD

**Issue by ivanlesko** [FlexMonkey/Filterpedia#7]
For us folks without iPads, it would be great to use filterpedia in the simulator.  Looks like this is related to MetalKit not being supported in the simulator.  

http://stackoverflow.com/questions/24086194/how-do-you-import-metal-in-swift

I bring this up because it may deter some people from buying your book, and I want you to sell a lot of copies of your book :-)

**Comment by FlexMonkey** [comment]
Hi Ivan,

Many thanks for raising this. I've wrapped the Metal filters inside some conditionals and now I can build and target both simulator iPads and "real" iPads. 

Cheers!

Simon
