### ISSUE TITLE
Vector slider 

### ISSUE THREAD

**Issue by Tippit** [FlexMonkey/Filterpedia#8]
Hi,

Very very good job :)

Is it possible to use VectorSlider in Objective C project?

**Comment by FlexMonkey** [comment]
To the best of my knowledge, yes. However, I have no Objective C experience, so I don't know how to do it I'm afraid :)

Simon

**Comment by Tippit** [comment]
Thank’s :) Anyway you have done a very good job!

-- 
Claude Bezeaud
Sent with Airmail

On 11 mars 2016 at 17:20:59, simon gladman (notifications@github.com) wrote:

Closed #8.
